/**
 * Writes src/game-data/champions.ts from Data Dragon, and downloads the self-hosted icons into
 * public/game/.
 *
 * Match data names a champion by its numeric key; showing it needs the name and the image file.
 * Those used to come from a tRPC route that downloaded 846 KB of Data Dragon JSON every hour to
 * answer that one question, and every champion image on a page ran its own query for it. The
 * answer changes only when Riot releases a champion, so it lives in the repository instead.
 *
 * Run it after a champion release: `bun run --cwd apps/app generate:game-data`. Until then a new
 * champion shows the placeholder rather than breaking the page.
 *
 * The icons — rank crests, role icons, objective icons — come from Community Dragon, pinned to the
 * version matching the patch rather than `latest`, which is a moving alias. The list of files is
 * `LOCAL_ASSETS` in src/utils/asset-urls.ts, the same module that hands their paths to components.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { LOCAL_ASSETS } from "../src/utils/asset-urls";

const DD = "https://ddragon.leagueoflegends.com";
const CDRAGON = "https://raw.communitydragon.org";
const APP_DIR = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const OUT = join(APP_DIR, "src", "game-data", "champions.ts");
const PUBLIC_DIR = join(APP_DIR, "public");

interface ChampionJson {
  data: Record<string, { key: string; name: string; image: { full: string } }>;
}

async function json<T>(url: string): Promise<T> {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${response.status} ${url}`);
  return response.json() as Promise<T>;
}

const [patch] = await json<string[]>(`${DD}/api/versions.json`);
if (!patch) throw new Error("versions.json listed no patch");

const { data } = await json<ChampionJson>(
  `${DD}/cdn/${patch}/data/en_US/champion.json`,
);

const entries = Object.values(data)
  .map((champion) => ({
    key: Number(champion.key),
    name: champion.name,
    image: champion.image.full,
  }))
  .sort((a, b) => a.key - b.key);

if (entries.length < 150 || entries.some((c) => !Number.isInteger(c.key))) {
  throw new Error(
    `Unexpected champion data: ${entries.length} entries — refusing to write`,
  );
}

const lines = entries.map(
  (c) =>
    `  ${c.key}: { name: ${JSON.stringify(c.name)}, image: ${JSON.stringify(c.image)} },`,
);

writeFileSync(
  OUT,
  `// Generated by scripts/generate-game-data.ts from Data Dragon ${patch}. Do not edit by hand.

/** The patch this file was generated from; the fallback when the live patch cannot be fetched. */
export const GENERATED_PATCH = ${JSON.stringify(patch)};

/** Every champion, by the numeric key match data uses for it. */
export const CHAMPIONS: Record<number, { name: string; image: string }> = {
${lines.join("\n")}
};
`,
);

console.log(`Wrote ${entries.length} champions from patch ${patch} to ${OUT}`);

// Community Dragon names its versions major.minor, so 16.19.1 is 16.19.
const assetVersion = patch.split(".").slice(0, 2).join(".");

for (const asset of LOCAL_ASSETS) {
  const url = `${CDRAGON}/${assetVersion}/${asset.source}`;
  const response = await fetch(url);
  const type = response.headers.get("content-type") ?? "";
  if (!response.ok || !type.startsWith("image/")) {
    throw new Error(`${response.status} ${type} ${url}`);
  }
  const file = join(PUBLIC_DIR, asset.path);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, Buffer.from(await response.arrayBuffer()));
}

console.log(
  `Wrote ${LOCAL_ASSETS.length} icons from Community Dragon ${assetVersion} to public/game/`,
);
