/**
 * Writes src/game-data/champions.ts from Data Dragon, and downloads the self-hosted icons into
 * public/game/.
 *
 * Match data names a champion by its numeric key; showing it needs the name and the image file.
 * Those used to come from a tRPC route that downloaded 846 KB of Data Dragon JSON every hour to
 * answer that one question, and every champion image on a page ran its own query for it. The
 * answer changes only when Riot releases a champion, so it lives in the repository instead.
 *
 * Run it after a champion release: `bun run --cwd apps/app generate:game-data`. Until then a new
 * champion shows the placeholder rather than breaking the page.
 *
 * The icons — rank crests, role icons, objective icons — come from Community Dragon, pinned to the
 * version matching the patch rather than `latest`, which is a moving alias. Which files to fetch is
 * `SELF_HOSTED_PATHS`, the list the app's own URL functions produce; where each comes from on
 * Community Dragon is this script's business alone.
 *
 * Everything is downloaded and checked before anything is written, so a failure halfway leaves the
 * repository as it was rather than a new champion list beside old icons.
 *
 * A re-run can change icon bytes without changing a pixel: Community Dragon sits behind Cloudflare,
 * which sometimes serves a losslessly recompressed PNG (`cf-polished`), depending on its edge cache.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { SELF_HOSTED_PATHS } from "@/utils/asset-urls";

const DD = "https://ddragon.leagueoflegends.com";
const CDRAGON = "https://raw.communitydragon.org";
const APP_DIR = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const OUT = join(APP_DIR, "src", "game-data", "champions.ts");
const PUBLIC_DIR = join(APP_DIR, "public");

/** Community Dragon's folder for each kind of self-hosted icon, and its file naming. */
function cdragonSource(path: string): string {
  const file = path.split("/").pop();
  if (path.startsWith("/game/ranks/")) {
    return `plugins/rcp-fe-lol-static-assets/global/default/images/ranked-mini-crests/${file}`;
  }
  if (path.startsWith("/game/roles/")) {
    return `plugins/rcp-fe-lol-clash/global/default/assets/images/position-selector/positions/icon-position-${file}`;
  }
  if (path.startsWith("/game/objectives/")) {
    return `plugins/rcp-fe-lol-match-history/global/default/${file}`;
  }
  throw new Error(`No Community Dragon source for ${path}`);
}

interface ChampionJson {
  data: Record<string, { key: string; name: string; image: { full: string } }>;
}

async function json<T>(url: string): Promise<T> {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${response.status} ${url}`);
  return response.json() as Promise<T>;
}

const [patch] = await json<string[]>(`${DD}/api/versions.json`);
if (!patch) throw new Error("versions.json listed no patch");

const { data } = await json<ChampionJson>(
  `${DD}/cdn/${patch}/data/en_US/champion.json`,
);

const entries = Object.values(data)
  .map((champion) => ({
    key: Number(champion.key),
    name: champion.name,
    image: champion.image.full,
  }))
  .sort((a, b) => a.key - b.key);

if (entries.length < 150 || entries.some((c) => !Number.isInteger(c.key))) {
  throw new Error(
    `Unexpected champion data: ${entries.length} entries — refusing to write`,
  );
}

const lines = entries.map(
  (c) =>
    `  ${c.key}: { name: ${JSON.stringify(c.name)}, image: ${JSON.stringify(c.image)} },`,
);

const championsSource = `// Generated by scripts/generate-game-data.ts from Data Dragon ${patch}. Do not edit by hand.

/** The patch this file was generated from; the fallback when the live patch cannot be fetched. */
export const GENERATED_PATCH = ${JSON.stringify(patch)};

/** Every champion, by the numeric key match data uses for it. */
export const CHAMPIONS: Record<number, { name: string; image: string }> = {
${lines.join("\n")}
};
`;

// Community Dragon names its versions major.minor, so 16.19.1 is 16.19.
const assetVersion = patch.split(".").slice(0, 2).join(".");

const icons = await Promise.all(
  SELF_HOSTED_PATHS.map(async (path) => {
    const url = `${CDRAGON}/${assetVersion}/${cdragonSource(path)}`;
    const response = await fetch(url);
    const type = response.headers.get("content-type") ?? "";
    if (!response.ok || !type.startsWith("image/")) {
      throw new Error(`${response.status} ${type} ${url}`);
    }
    return { path, bytes: Buffer.from(await response.arrayBuffer()) };
  }),
);

// Everything fetched and checked; only now touch the repository.
writeFileSync(OUT, championsSource);
for (const icon of icons) {
  const file = join(PUBLIC_DIR, icon.path);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, icon.bytes);
}

console.log(
  `Wrote ${entries.length} champions from Data Dragon ${patch}, and ${icons.length} icons from Community Dragon ${assetVersion}`,
);
