/**
 * Writes src/game-data/champions.ts from Data Dragon.
 *
 * Match data names a champion by its numeric key; showing it needs the name and the image file.
 * Those used to come from a tRPC route that downloaded 846 KB of Data Dragon JSON every hour to
 * answer that one question, and every champion image on a page ran its own query for it. The
 * answer changes only when Riot releases a champion, so it lives in the repository instead.
 *
 * Run it after a champion release: `bun run --cwd apps/app generate:game-data`. Until then a new
 * champion shows the placeholder rather than breaking the page.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const DD = "https://ddragon.leagueoflegends.com";
const OUT = join(
  fileURLToPath(new URL(".", import.meta.url)),
  "..",
  "src",
  "game-data",
  "champions.ts",
);

interface ChampionJson {
  data: Record<string, { key: string; name: string; image: { full: string } }>;
}

async function json<T>(url: string): Promise<T> {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${response.status} ${url}`);
  return response.json() as Promise<T>;
}

const [patch] = await json<string[]>(`${DD}/api/versions.json`);
if (!patch) throw new Error("versions.json listed no patch");

const { data } = await json<ChampionJson>(
  `${DD}/cdn/${patch}/data/en_US/champion.json`,
);

const entries = Object.values(data)
  .map((champion) => ({
    key: Number(champion.key),
    name: champion.name,
    image: champion.image.full,
  }))
  .sort((a, b) => a.key - b.key);

if (entries.length < 150 || entries.some((c) => !Number.isInteger(c.key))) {
  throw new Error(
    `Unexpected champion data: ${entries.length} entries — refusing to write`,
  );
}

const lines = entries.map(
  (c) =>
    `  ${c.key}: { name: ${JSON.stringify(c.name)}, image: ${JSON.stringify(c.image)} },`,
);

writeFileSync(
  OUT,
  `// Generated by scripts/generate-game-data.ts from Data Dragon ${patch}. Do not edit by hand.

/** The patch this file was generated from; the fallback when the live patch cannot be fetched. */
export const GENERATED_PATCH = ${JSON.stringify(patch)};

/** Every champion, by the numeric key match data uses for it. */
export const CHAMPIONS: Record<number, { name: string; image: string }> = {
${lines.join("\n")}
};
`,
);

console.log(`Wrote ${entries.length} champions from patch ${patch} to ${OUT}`);
